import { execSync } from 'node:child_process'
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'

function readPackageVersion(): string {
  const raw = readFileSync(resolve('package.json'), 'utf8')
  const parsed = JSON.parse(raw) as { version?: string }
  return parsed.version && parsed.version.trim() ? parsed.version.trim() : '0.0.0'
}

function readCommit(): string {
  const fromEnv = process.env.GITHUB_SHA?.trim() || process.env.GIT_COMMIT?.trim()
  if (fromEnv) {
    return fromEnv.slice(0, 12)
  }
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
  } catch {
    return 'unknown'
  }
}

function collectBuildInfo(): { version: string; buildTime: string; commit: string } {
  return {
    version: readPackageVersion(),
    buildTime: new Date().toISOString(),
    commit: readCommit()
  }
}

const buildInfo = collectBuildInfo()
const buildInfoDefine = {
  __CS_BUILD_INFO__: JSON.stringify(buildInfo)
}

function writeGeneratedBuildInfo(): void {
  const destDir = resolve('src/shared')
  mkdirSync(destDir, { recursive: true })
  writeFileSync(
    join(destDir, 'buildInfo.generated.ts'),
    `/* generated by electron-vite — do not edit */\nexport const GENERATED_BUILD_INFO = ${JSON.stringify(buildInfo, null, 2)} as const\n`
  )
  const outDir = resolve('out')
  mkdirSync(outDir, { recursive: true })
  writeFileSync(join(outDir, 'build-info.json'), `${JSON.stringify(buildInfo, null, 2)}\n`)
}

writeGeneratedBuildInfo()

function copyGradleWrapperPlugin() {
  return {
    name: 'copy-gradle-wrapper',
    closeBundle(): void {
      writeGeneratedBuildInfo()
      const dest = resolve('out/main/wrapper')
      mkdirSync(dest, { recursive: true })
      for (const name of ['gradle-wrapper.jar', 'gradlew', 'gradlew.bat']) {
        copyFileSync(resolve('src/main/codegen/fabric/wrapper', name), join(dest, name))
      }
    }
  }
}

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin(), copyGradleWrapperPlugin()],
    define: buildInfoDefine,
    resolve: {
      alias: {
        '@shared': resolve('src/shared'),
        '@main': resolve('src/main')
      }
    }
  },
  preload: {
    plugins: [externalizeDepsPlugin()],
    define: buildInfoDefine,
    resolve: {
      alias: {
        '@shared': resolve('src/shared')
      }
    }
  },
  renderer: {
    define: buildInfoDefine,
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src'),
        '@shared': resolve('src/shared')
      }
    },
    plugins: [react(), tailwindcss()]
  }
})
