/**
 * Target-version vanilla registries used for recipe/enchantment/terrain validation.
 * Unknown ids are rejected in place. They are never rewritten to iron, stick, or another default.
 */

export const REGISTRY_MINECRAFT_VERSION = '1.21.1'

const VANILLA_ITEMS_1_21_1 = [
  'minecraft:stick',
  'minecraft:cobblestone',
  'minecraft:stone',
  'minecraft:dirt',
  'minecraft:grass_block',
  'minecraft:sand',
  'minecraft:gravel',
  'minecraft:iron_ingot',
  'minecraft:gold_ingot',
  'minecraft:diamond',
  'minecraft:coal',
  'minecraft:oak_planks',
  'minecraft:string',
  'minecraft:leather',
  'minecraft:paper',
  'minecraft:glass',
  'minecraft:wheat',
  'minecraft:egg',
  'minecraft:redstone',
  'minecraft:iron_nugget',
  'minecraft:gold_nugget',
  'minecraft:flint',
  'minecraft:bone',
  'minecraft:slime_ball',
  'minecraft:clay_ball',
  'minecraft:brick',
  'minecraft:charcoal',
  'minecraft:copper_ingot',
  'minecraft:amethyst_shard',
  'minecraft:netherite_ingot',
  'minecraft:netherite_scrap',
  'minecraft:netherite_sword',
  'minecraft:netherite_axe',
  'minecraft:netherite_pickaxe',
  'minecraft:netherite_shovel',
  'minecraft:netherite_hoe',
  'minecraft:netherite_helmet',
  'minecraft:netherite_chestplate',
  'minecraft:netherite_leggings',
  'minecraft:netherite_boots',
  'minecraft:heavy_core',
  'minecraft:breeze_rod',
  'minecraft:mace',
  'minecraft:wind_charge',
  'minecraft:enchanted_golden_apple',
  'minecraft:golden_apple',
  'minecraft:apple',
  'minecraft:diamond_sword',
  'minecraft:iron_sword',
  'minecraft:golden_sword',
  'minecraft:stone_sword',
  'minecraft:wooden_sword',
  'minecraft:diamond_axe',
  'minecraft:iron_axe',
  'minecraft:bow',
  'minecraft:crossbow',
  'minecraft:trident',
  'minecraft:shield',
  'minecraft:ender_pearl',
  'minecraft:ender_eye',
  'minecraft:blaze_rod',
  'minecraft:blaze_powder',
  'minecraft:nether_star',
  'minecraft:nether_brick',
  'minecraft:obsidian',
  'minecraft:crying_obsidian',
  'minecraft:crying_obsidian',
  'minecraft:echo_shard',
  'minecraft:disc_fragment_5',
  'minecraft:recovery_compass',
  'minecraft:compass',
  'minecraft:clock',
  'minecraft:lapis_lazuli',
  'minecraft:emerald',
  'minecraft:quartz',
  'minecraft:prismarine_shard',
  'minecraft:prismarine_crystals',
  'minecraft:nautilus_shell',
  'minecraft:heart_of_the_sea',
  'minecraft:phantom_membrane',
  'minecraft:feather',
  'minecraft:gunpowder',
  'minecraft:glowstone_dust',
  'minecraft:redstone_block',
  'minecraft:iron_block',
  'minecraft:gold_block',
  'minecraft:diamond_block',
  'minecraft:netherite_block',
  'minecraft:copper_block',
  'minecraft:raw_iron',
  'minecraft:raw_gold',
  'minecraft:raw_copper',
  'minecraft:ancient_debris',
  'minecraft:ender_chest',
  'minecraft:chest',
  'minecraft:barrel',
  'minecraft:book',
  'minecraft:enchanted_book',
  'minecraft:experience_bottle',
  'minecraft:glass_bottle',
  'minecraft:potion',
  'minecraft:splash_potion',
  'minecraft:lingering_potion',
  'minecraft:totem_of_undying',
  'minecraft:netherite_upgrade_smithing_template',
  'minecraft:trial_key',
  'minecraft:ominous_trial_key',
  'minecraft:ominous_bottle',
  'minecraft:bolt_armor_trim_smithing_template',
  'minecraft:flow_armor_trim_smithing_template',
  'minecraft:guster_banner_pattern',
  'minecraft:flow_banner_pattern',
  'minecraft:flow_pottery_sherd',
  'minecraft:guster_pottery_sherd',
  'minecraft:scrape_pottery_sherd',
  'minecraft:armadillo_scute',
  'minecraft:wolf_armor',
  'minecraft:oak_log',
  'minecraft:spruce_log',
  'minecraft:birch_log',
  'minecraft:jungle_log',
  'minecraft:acacia_log',
  'minecraft:dark_oak_log',
  'minecraft:mangrove_log',
  'minecraft:cherry_log',
  'minecraft:bamboo',
  'minecraft:bamboo_block',
  'minecraft:crimson_stem',
  'minecraft:warped_stem',
  'minecraft:white_wool',
  'minecraft:string',
  'minecraft:arrow',
  'minecraft:spectral_arrow',
  'minecraft:tipped_arrow',
  'minecraft:snowball',
  'minecraft:fire_charge',
  'minecraft:firework_rocket',
  'minecraft:lead',
  'minecraft:name_tag',
  'minecraft:saddle',
  'minecraft:oak_boat',
  'minecraft:minecart',
  'minecraft:hopper',
  'minecraft:dispenser',
  'minecraft:dropper',
  'minecraft:piston',
  'minecraft:sticky_piston',
  'minecraft:observer',
  'minecraft:redstone_torch',
  'minecraft:repeater',
  'minecraft:comparator',
  'minecraft:lever',
  'minecraft:stone_button',
  'minecraft:oak_button',
  'minecraft:tripwire_hook',
  'minecraft:daylight_detector',
  'minecraft:target',
  'minecraft:calibrated_sculk_sensor',
  'minecraft:sculk_sensor',
  'minecraft:sculk_catalyst',
  'minecraft:sculk_shrieker',
  'minecraft:sculk',
  'minecraft:vault',
  'minecraft:trial_spawner',
  'minecraft:crafter',
  'minecraft:copper_bulb',
  'minecraft:copper_grate',
  'minecraft:copper_door',
  'minecraft:copper_trapdoor',
  'minecraft:tuff',
  'minecraft:tuff_bricks',
  'minecraft:chiseled_tuff',
  'minecraft:polished_tuff',
  'minecraft:sponge',
  'minecraft:wet_sponge',
  'minecraft:ice',
  'minecraft:packed_ice',
  'minecraft:blue_ice',
  'minecraft:snow_block',
  'minecraft:snowball',
  'minecraft:clay',
  'minecraft:terracotta',
  'minecraft:white_concrete',
  'minecraft:glass_pane',
  'minecraft:iron_bars',
  'minecraft:chain',
  'minecraft:lantern',
  'minecraft:soul_lantern',
  'minecraft:torch',
  'minecraft:soul_torch',
  'minecraft:campfire',
  'minecraft:soul_campfire',
  'minecraft:crafting_table',
  'minecraft:furnace',
  'minecraft:blast_furnace',
  'minecraft:smoker',
  'minecraft:anvil',
  'minecraft:smithing_table',
  'minecraft:grindstone',
  'minecraft:enchanting_table',
  'minecraft:bookshelf',
  'minecraft:chiseled_bookshelf',
  'minecraft:lectern',
  'minecraft:loom',
  'minecraft:cartography_table',
  'minecraft:fletching_table',
  'minecraft:composter',
  'minecraft:cauldron',
  'minecraft:brewing_stand',
  'minecraft:beacon',
  'minecraft:conduit',
  'minecraft:lodestone',
  'minecraft:respawn_anchor',
  'minecraft:end_crystal',
  'minecraft:dragon_egg',
  'minecraft:dragon_head',
  'minecraft:wither_skeleton_skull',
  'minecraft:skeleton_skull',
  'minecraft:zombie_head',
  'minecraft:creeper_head',
  'minecraft:piglin_head',
  'minecraft:player_head',
  'minecraft:turtle_egg',
  'minecraft:sniffer_egg',
  'minecraft:frogspawn',
  'minecraft:honeycomb',
  'minecraft:honey_bottle',
  'minecraft:honey_block',
  'minecraft:slime_block',
  'minecraft:magma_cream',
  'minecraft:magma_block',
  'minecraft:ghast_tear',
  'minecraft:gunpowder',
  'minecraft:spider_eye',
  'minecraft:fermented_spider_eye',
  'minecraft:rotten_flesh',
  'minecraft:bone_meal',
  'minecraft:ink_sac',
  'minecraft:glow_ink_sac',
  'minecraft:coal_block',
  'minecraft:dried_kelp',
  'minecraft:dried_kelp_block',
  'minecraft:wheat_seeds',
  'minecraft:pumpkin_seeds',
  'minecraft:melon_seeds',
  'minecraft:beetroot_seeds',
  'minecraft:torchflower_seeds',
  'minecraft:pitcher_pod',
  'minecraft:nether_wart',
  'minecraft:chorus_fruit',
  'minecraft:popped_chorus_fruit',
  'minecraft:ender_pearl',
  'minecraft:shulker_shell',
  'minecraft:poppy',
  'minecraft:dandelion',
  'minecraft:short_grass',
  'minecraft:fern',
  'minecraft:dead_bush',
  'minecraft:vine',
  'minecraft:lily_pad',
  'minecraft:moss_block',
  'minecraft:moss_carpet',
  'minecraft:pale_moss_block',
  'minecraft:pale_oak_log',
  'minecraft:resin_clump',
  'minecraft:resin_brick',
  'minecraft:creaking_heart',
  'minecraft:open_eyeblossom',
  'minecraft:closed_eyeblossom',
  'minecraft:milk_bucket',
  'minecraft:water_bucket',
  'minecraft:lava_bucket',
  'minecraft:powder_snow_bucket',
  'minecraft:bucket',
  'minecraft:cod_bucket',
  'minecraft:salmon_bucket',
  'minecraft:tropical_fish_bucket',
  'minecraft:pufferfish_bucket',
  'minecraft:axolotl_bucket',
  'minecraft:tadpole_bucket',
  'minecraft:name_tag',
  'minecraft:writable_book',
  'minecraft:written_book',
  'minecraft:map',
  'minecraft:filled_map',
  'minecraft:firework_star',
  'minecraft:fire_charge',
  'minecraft:flint_and_steel',
  'minecraft:shears',
  'minecraft:brush',
  'minecraft:spyglass',
  'minecraft:goat_horn',
  'minecraft:music_disc_5',
  'minecraft:music_disc_creator',
  'minecraft:music_disc_precipice',
  'minecraft:music_disc_relic',
  'minecraft:ominous_trial_key',
  'minecraft:trial_key',
  'minecraft:wind_charge',
  'minecraft:breeze_rod',
  'minecraft:heavy_core',
  'minecraft:mace'
] as const

const uniqueItems = [...new Set(VANILLA_ITEMS_1_21_1)]

/** 1.21.1 item ids CraftStudio will accept as vanilla recipe ingredients. Stick stays first for editor defaults. */
export const VANILLA_ITEMS = uniqueItems as unknown as readonly string[]

const VANILLA_ITEM_SET = new Set(VANILLA_ITEMS)

export const TERRAIN_ALLOW_BLOCKS = [
  'minecraft:dirt',
  'minecraft:grass_block',
  'minecraft:stone',
  'minecraft:sand',
  'minecraft:gravel'
] as const

export const VANILLA_ENCHANTMENTS_1_21_1 = [
  'minecraft:protection',
  'minecraft:fire_protection',
  'minecraft:feather_falling',
  'minecraft:blast_protection',
  'minecraft:projectile_protection',
  'minecraft:respiration',
  'minecraft:aqua_affinity',
  'minecraft:thorns',
  'minecraft:depth_strider',
  'minecraft:frost_walker',
  'minecraft:binding_curse',
  'minecraft:soul_speed',
  'minecraft:swift_sneak',
  'minecraft:sharpness',
  'minecraft:smite',
  'minecraft:bane_of_arthropods',
  'minecraft:knockback',
  'minecraft:fire_aspect',
  'minecraft:looting',
  'minecraft:sweeping_edge',
  'minecraft:efficiency',
  'minecraft:silk_touch',
  'minecraft:unbreaking',
  'minecraft:fortune',
  'minecraft:power',
  'minecraft:punch',
  'minecraft:flame',
  'minecraft:infinity',
  'minecraft:luck_of_the_sea',
  'minecraft:lure',
  'minecraft:loyalty',
  'minecraft:impaling',
  'minecraft:riptide',
  'minecraft:channeling',
  'minecraft:multishot',
  'minecraft:quick_charge',
  'minecraft:piercing',
  'minecraft:density',
  'minecraft:breach',
  'minecraft:wind_burst',
  'minecraft:mending',
  'minecraft:vanishing_curse'
] as const

export const MACE_COMPATIBLE_ENCHANTMENTS = [
  'minecraft:density',
  'minecraft:breach',
  'minecraft:wind_burst',
  'minecraft:unbreaking',
  'minecraft:mending',
  'minecraft:vanishing_curse',
  'minecraft:fire_aspect',
  'minecraft:smite',
  'minecraft:bane_of_arthropods'
] as const

export const GENERIC_WEAPON_ENCHANTMENTS = [
  'minecraft:sharpness',
  'minecraft:smite',
  'minecraft:bane_of_arthropods',
  'minecraft:knockback',
  'minecraft:fire_aspect',
  'minecraft:looting',
  'minecraft:unbreaking',
  'minecraft:mending',
  'minecraft:vanishing_curse'
] as const

export function normalizeVanillaId(id: string): string {
  const trimmed = id.trim()
  if (!trimmed) {
    return trimmed
  }
  return trimmed.includes(':') ? trimmed : `minecraft:${trimmed}`
}

export function isVanillaItemId(id: string, _minecraftVersion = REGISTRY_MINECRAFT_VERSION): boolean {
  return VANILLA_ITEM_SET.has(normalizeVanillaId(id))
}

export function isVanillaEnchantmentId(id: string): boolean {
  return (VANILLA_ENCHANTMENTS_1_21_1 as readonly string[]).includes(normalizeVanillaId(id))
}

export function compatibleEnchantmentsFor(kind: 'mace' | 'generic'): readonly string[] {
  return kind === 'mace' ? MACE_COMPATIBLE_ENCHANTMENTS : GENERIC_WEAPON_ENCHANTMENTS
}

export function isCompatibleEnchantment(id: string, kind: 'mace' | 'generic'): boolean {
  return compatibleEnchantmentsFor(kind).includes(normalizeVanillaId(id))
}

export function isTerrainAllowBlock(id: string): boolean {
  return (TERRAIN_ALLOW_BLOCKS as readonly string[]).includes(normalizeVanillaId(id))
}
